# Utiliza una imagen base de Node.js
FROM node:14

# Instala TypeScript globalmente
RUN npm install -g ts-node

# Establece el directorio de trabajo dentro del contenedor
WORKDIR /app

# Copia el archivo package.json y package-lock.json al directorio de trabajo
COPY ./server/package*.json ./

COPY ./server .

# Instala las dependencias
RUN npm install

# Compila la aplicación TypeScript
RUN npm run build

# Expone el puerto en el que se ejecutará la aplicación
EXPOSE 3000

# Comando para ejecutar la aplicación
CMD [ "npm", "run", "dev" ]